<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'

type User = { id:number; username:string; role:string; active:boolean; password_change_required:boolean; created_at:string }
type Task = { id:string; user_id:number; prompt:string; status:string; codex_session_id?:string; final_output:string; error:string; created_at:string; updated_at:string; diff?:string; events?:any[] }
const setupNeeded=ref(false), loading=ref(true), user=ref<User|null>(null), csrf=ref(''), error=ref('')
const loginForm=ref({username:'',password:''}), setupForm=ref({token:'',username:'admin',password:''}), passwordForm=ref({current_password:'',new_password:''})
const tasks=ref<Task[]>([]), selected=ref<Task|null>(null), prompt=ref(''), events=ref<any[]>([]), system=ref<any>({}), users=ref<User[]>([]), activeTab=ref('tasks'), userForm=ref({username:'',role:'user'})
let source:EventSource|null=null, refreshTimer:any=null, codexPoll:any=null
const deviceLogin=ref<any>({running:false,authenticated:false,device_url:'',user_code:'',message:''})
const isAdmin=computed(()=>user.value?.role==='admin')
async function api(path:string, options:RequestInit={}) {
  const headers=new Headers(options.headers||{})
  if(options.body && !headers.has('Content-Type')) headers.set('Content-Type','application/json')
  if(csrf.value && !['GET','HEAD'].includes((options.method||'GET').toUpperCase())) headers.set('X-CSRF-Token',csrf.value)
  const r=await fetch(path,{...options,headers,credentials:'same-origin'})
  const body=await r.json().catch(()=>({detail:r.statusText}))
  if(!r.ok) throw new Error(body.detail||`HTTP ${r.status}`)
  return body
}
async function init(){
  loading.value=true
  try {
    const s=await api('/api/setup/status'); setupNeeded.value=s.needs_admin
    if(!setupNeeded.value){try{const m=await api('/api/auth/me');user.value=m.user;csrf.value=m.csrf_token}catch{user.value=null}}
    if(user.value && !user.value.password_change_required) await loadAll()
  } catch(e:any){error.value=e.message} finally{loading.value=false}
}
async function bootstrap(){try{await api('/api/setup/bootstrap',{method:'POST',body:JSON.stringify(setupForm.value)});ElMessage.success('管理员已创建，请登录');setupNeeded.value=false;setupForm.value.token=''}catch(e:any){ElMessage.error(e.message)}}
async function login(){try{const x=await api('/api/auth/login',{method:'POST',body:JSON.stringify(loginForm.value)});user.value=x.user;csrf.value=x.csrf_token;loginForm.value.password='';if(user.value?.password_change_required){passwordForm.value.current_password='';return}await loadAll()}catch(e:any){ElMessage.error(e.message)}}
async function changePassword(){try{const x=await api('/api/auth/password',{method:'POST',body:JSON.stringify(passwordForm.value)});user.value=x.user;passwordForm.value={current_password:'',new_password:''};ElMessage.success('密码已更新');await loadAll()}catch(e:any){ElMessage.error(e.message)}}
async function logout(){try{await api('/api/auth/logout',{method:'POST'})}catch{}if(source)source.close();user.value=null;csrf.value='';selected.value=null;tasks.value=[]}
async function loadAll(){await Promise.all([loadTasks(),loadSystem()]);if(isAdmin.value)await loadUsers();if(!refreshTimer)refreshTimer=setInterval(()=>{loadTasks();loadSystem()},5000)}
async function loadTasks(){try{tasks.value=await api('/api/tasks');if(selected.value){const latest=tasks.value.find(t=>t.id===selected.value?.id);if(latest)selected.value=latest}}catch(e:any){if(e.message.includes('登录'))logout()}}
async function loadSystem(){try{system.value=await api('/api/system/status')}catch{}}
async function loadUsers(){try{users.value=await api('/api/admin/users')}catch(e:any){ElMessage.error(e.message)}}
async function refreshCodexLogin(){try{deviceLogin.value=await api('/api/admin/codex/login/status');if(deviceLogin.value.authenticated){if(codexPoll)clearInterval(codexPoll);codexPoll=null;await loadSystem();ElMessage.success('ChatGPT 账号已连接')}}catch{}}
async function startCodexLogin(){try{deviceLogin.value=await api('/api/admin/codex/login/start',{method:'POST'});if(!codexPoll)codexPoll=setInterval(refreshCodexLogin,2000)}catch(e:any){ElMessage.error(e.message)}}
async function cancelCodexLogin(){try{deviceLogin.value=await api('/api/admin/codex/login/cancel',{method:'POST'});if(codexPoll)clearInterval(codexPoll);codexPoll=null}catch(e:any){ElMessage.error(e.message)}}
async function createTask(){if(!prompt.value.trim())return;try{const t=await api('/api/tasks',{method:'POST',body:JSON.stringify({prompt:prompt.value.trim()})});prompt.value='';await loadTasks();await openTask(t.id)}catch(e:any){ElMessage.error(e.message)}}
async function openTask(id:string){if(source){source.close();source=null}try{selected.value=await api(`/api/tasks/${id}`);events.value=selected.value?.events||[];source=new EventSource(`/api/tasks/${id}/events?after=${events.value.length}`,{withCredentials:true});source.onmessage=(ev)=>{try{const x=JSON.parse(ev.data);events.value.push(x);if(x.type==='thread.started'&&selected.value){selected.value.codex_session_id=x.data.thread_id||selected.value.codex_session_id}loadTasks()}catch{}};source.addEventListener('end',()=>{source?.close();source=null;loadTasks();openTaskData(id)});source.onerror=()=>{source?.close();source=null;loadTasks()}}catch(e:any){ElMessage.error(e.message)}}
async function openTaskData(id:string){try{selected.value=await api(`/api/tasks/${id}`);events.value=selected.value.events||[]}catch{}}
async function cancelTask(){if(!selected.value)return;try{await api(`/api/tasks/${selected.value.id}/cancel`,{method:'POST'});ElMessage.success('已请求取消');await loadTasks()}catch(e:any){ElMessage.error(e.message)}}
async function resumeTask(){if(!selected.value)return;try{const {value}=await ElMessageBox.prompt('输入继续指令','继续 Codex 会话',{inputType:'textarea',inputPlaceholder:'例如：继续完成剩余工作，并运行相关检查'});const t=await api(`/api/tasks/${selected.value.id}/resume`,{method:'POST',body:JSON.stringify({prompt:value})});await loadTasks();await openTask(t.id)}catch(e:any){if(e!=='cancel')ElMessage.error((e as any).message||String(e))}}
async function addUser(){if(!userForm.value.username.trim())return;try{const x=await api('/api/admin/users',{method:'POST',body:JSON.stringify(userForm.value)});await loadUsers();await ElMessageBox.alert(`临时密码：${x.temporary_password}\n请安全复制给用户；首次登录必须修改。`,'用户已创建',{confirmButtonText:'知道了'}) ;userForm.value={username:'',role:'user'}}catch(e:any){ElMessage.error(e.message)}}
async function toggleUser(u:User){try{await api(`/api/admin/users/${u.id}?active=${!u.active}&role=${u.role}`,{method:'PATCH'});await loadUsers()}catch(e:any){ElMessage.error(e.message)}}
async function resetUser(u:User){try{await ElMessageBox.confirm(`重置 ${u.username} 的登录密码？`,'确认');const x=await api(`/api/admin/users/${u.id}/reset-password`,{method:'POST'});await ElMessageBox.alert(`临时密码：${x.temporary_password}\n用户下次登录后必须修改。`,'密码已重置')}catch(e:any){if(e!=='cancel')ElMessage.error((e as any).message||String(e))}}
function statusType(s:string){return ({queued:'info',running:'warning',cancel_requested:'warning',succeeded:'success',failed:'danger',cancelled:'info',interrupted:'danger'} as any)[s]||'info'}
function statusLabel(s:string){return ({queued:'排队中',running:'运行中',cancel_requested:'取消中',succeeded:'已完成',failed:'失败',cancelled:'已取消',interrupted:'已中断'} as any)[s]||s}
function time(v:string){return v?new Date(v).toLocaleString():'—'}
function pretty(e:any){const d=e?.data||{};if(d.item?.type==='agent_message')return d.item.text||JSON.stringify(e);if(d.text)return d.text;return JSON.stringify(e,null,2)}
onMounted(init)
onUnmounted(()=>{if(source)source.close();if(refreshTimer)clearInterval(refreshTimer);if(codexPoll)clearInterval(codexPoll)})
</script>

<template>
  <div v-if="loading" class="login-wrap"><el-card>正在连接控制台…</el-card></div>
  <div v-else-if="setupNeeded" class="login-wrap"><div class="login-card"><div class="brand"><span class="brand-mark">C</span> Codex 控制台</div><h1 style="margin-top:24px">首次初始化</h1><p>使用服务器生成的一次性初始化令牌创建管理员。管理员密码至少 12 位。</p><el-form label-position="top"><el-form-item label="初始化令牌"><el-input v-model="setupForm.token" show-password /></el-form-item><el-form-item label="管理员用户名"><el-input v-model="setupForm.username" /></el-form-item><el-form-item label="管理员密码"><el-input v-model="setupForm.password" type="password" show-password /></el-form-item><el-button type="primary" style="width:100%" @click="bootstrap">创建管理员</el-button></el-form></div></div>
  <div v-else-if="!user" class="login-wrap"><div class="login-card"><div class="brand"><span class="brand-mark">C</span> Codex 控制台</div><h1 style="margin-top:24px">登录</h1><p>使用管理员或已创建的用户账号登录。</p><el-form label-position="top" @submit.prevent="login"><el-form-item label="用户名"><el-input v-model="loginForm.username" autocomplete="username" /></el-form-item><el-form-item label="密码"><el-input v-model="loginForm.password" type="password" show-password autocomplete="current-password" @keyup.enter="login" /></el-form-item><el-button type="primary" style="width:100%" @click="login">登录</el-button></el-form></div></div>
  <div v-else-if="user.password_change_required" class="login-wrap"><div class="login-card"><div class="brand"><span class="brand-mark">C</span> Codex 控制台</div><h1 style="margin-top:24px">设置新密码</h1><p>这是临时密码。请设置至少 12 位的新密码后继续。</p><el-form label-position="top"><el-form-item label="新密码"><el-input v-model="passwordForm.new_password" type="password" show-password /></el-form-item><el-button type="primary" style="width:100%" @click="changePassword">更新密码</el-button></el-form></div></div>
  <div v-else class="shell">
    <header class="topbar"><div class="brand"><span class="brand-mark">C</span> Codex 控制台</div><div class="top-actions"><el-tag :type="system.codex?.authenticated?'success':'warning'">{{system.codex?.authenticated?'Codex 已登录':'Codex 未登录'}}</el-tag><span>{{user.username}} · {{user.role==='admin'?'管理员':'用户'}}</span><el-button text @click="logout">退出</el-button></div></header>
    <main class="layout"><div class="tabs"><el-button :type="activeTab==='tasks'?'primary':'default'" @click="activeTab='tasks'">任务</el-button><el-button v-if="isAdmin" :type="activeTab==='users'?'primary':'default'" @click="activeTab='users';loadUsers()">用户管理</el-button></div>
      <template v-if="activeTab==='tasks'"><div v-if="isAdmin" class="card codex-login-card"><div class="section-head"><div><h2>ChatGPT / Codex 账号</h2><div class="muted">使用你的 Plus 账号进行设备登录；无需 API key。授权在 ChatGPT 官方页面完成。</div></div><el-button v-if="!deviceLogin.running" type="primary" @click="startCodexLogin">{{system.codex?.authenticated?'重新登录':'连接 ChatGPT 账号'}}</el-button><el-button v-else type="danger" plain @click="cancelCodexLogin">取消登录</el-button></div><div v-if="deviceLogin.running || deviceLogin.authenticated" class="device-login"><div>{{deviceLogin.message||'等待账号授权'}}</div><div v-if="deviceLogin.user_code" class="device-code">{{deviceLogin.user_code}}</div><el-link v-if="deviceLogin.device_url" :href="deviceLogin.device_url" target="_blank" rel="noopener noreferrer" type="primary">打开 OpenAI 设备授权页面</el-link><div class="muted">在授权页面输入上方代码。不要把设备代码发给他人。</div></div></div><div class="status-line"><span class="dot" :class="system.codex?.authenticated?'ok':'bad'"></span><span>{{system.codex?.message||'正在检查 Codex 状态'}}</span><el-tag v-if="system.workspace_git" size="small" type="success">Git 工作区已配置</el-tag><el-tag v-else size="small" type="warning">尚未配置 Git 仓库</el-tag></div>
        <div class="grid"><section class="card"><div class="section-head"><h2>任务历史</h2><span class="header-note">最多显示最近 200 条</span></div><div v-if="tasks.length" class="task-list"><div v-for="t in tasks" :key="t.id" class="task-row" :class="{selected:selected?.id===t.id}" @click="openTask(t.id)"><div class="task-row-head"><div class="task-prompt">{{t.prompt}}</div><el-tag :type="statusType(t.status)" size="small">{{statusLabel(t.status)}}</el-tag></div><div class="task-meta"><span>{{time(t.created_at)}}</span><span v-if="isAdmin">用户 #{{t.user_id}}</span><span v-if="t.codex_session_id">会话 {{t.codex_session_id.slice(0,12)}}…</span></div></div></div><el-empty v-else description="还没有任务" /></section>
          <section class="card"><h2>提交新任务</h2><el-input v-model="prompt" type="textarea" :rows="8" maxlength="20000" show-word-limit placeholder="描述你希望 Codex 在配置的 Git 仓库中完成什么…" /><div style="display:flex;justify-content:flex-end;margin-top:14px"><el-button type="primary" :disabled="!system.codex?.authenticated||!system.workspace_git" @click="createTask">提交任务</el-button></div><p class="muted">任务在独立 Git worktree 中运行；不会自动合并或部署。</p></section>
          <section v-if="selected" class="card" style="grid-column:1/-1"><div class="section-head"><h2>任务详情</h2><div class="task-actions"><el-button v-if="['queued','running','cancel_requested'].includes(selected.status)" type="danger" plain @click="cancelTask">取消</el-button><el-button v-if="['succeeded','failed','interrupted','cancelled'].includes(selected.status)&&selected.codex_session_id" @click="resumeTask">继续会话</el-button></div></div><div class="muted" style="margin-bottom:10px">{{selected.prompt}}</div><div v-if="selected.final_output" class="output" style="margin-bottom:16px">{{selected.final_output}}</div><div class="log"><template v-for="(e,i) in events" :key="i">{{e.type}} · {{pretty(e)}}
</template><span v-if="!events.length">等待 Codex 事件…</span></div><h2 style="margin-top:18px">Git diff</h2><pre class="log" style="height:240px">{{selected.diff||'尚无改动'}}</pre><div v-if="selected.error" style="margin-top:12px;color:#d44">{{selected.error}}</div></section>
        </div></template>
      <section v-else class="card"><div class="section-head"><h2>用户管理</h2><span class="muted">不开放公开注册；普通用户仅查看自己的任务</span></div><div style="display:flex;gap:10px;max-width:600px;margin-bottom:20px"><el-input v-model="userForm.username" placeholder="新用户名"/><el-select v-model="userForm.role" style="width:150px"><el-option label="普通用户" value="user"/><el-option label="管理员" value="admin"/></el-select><el-button type="primary" @click="addUser">创建用户</el-button></div><el-table :data="users" class="user-table"><el-table-column prop="username" label="用户名"/><el-table-column prop="role" label="角色"><template #default="s">{{s.row.role==='admin'?'管理员':'普通用户'}}</template></el-table-column><el-table-column label="状态"><template #default="s"><el-tag :type="s.row.active?'success':'info'">{{s.row.active?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column prop="created_at" label="创建时间" min-width="180"><template #default="s">{{time(s.row.created_at)}}</template></el-table-column><el-table-column label="操作" min-width="220"><template #default="s"><el-button size="small" @click="resetUser(s.row)">重置密码</el-button><el-button size="small" :type="s.row.active?'danger':'success'" @click="toggleUser(s.row)">{{s.row.active?'停用':'启用'}}</el-button></template></el-table-column></el-table></section>
    </main>
  </div>
</template>
